sudo: false
language: python
install:
- pip install mkdocs mkdocs-material
script:
- git clean -f -d -x;
- |
  while sleep 2m; do
    echo "====[ $SECONDS seconds running... ]===="
  done &
- mkdocs build -q
deploy:
  provider: script
  script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; else echo "PR skip deploy"; fi
  on:
    branch: master