sudo: false
language: python
install:
- pip install mkdocs mkdocs-material
script:
- git clean -f -d -x;
- travis_wait 30 ./script.sh
deploy:
  provider: script
  script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; else echo "PR skip deploy"; fi
  on:
    branch: master
env:
  matrix:
    secure: a6HfEw+WdRYY2jAi1yqZPPb9ZgK1HI0lllqCPYioCLSp6DlalOHvZFzinYjBGtHSJAqCbc5r1fMrktgAQ/8k8Noygff25Xa/bi/OteyxY2Xi6cZeqnc/r++kMNJYwtNEc/OGjE3K7UrG9gjuLr8PX+BkPwP/Y0NCyhToXzzJognmOUxRREHjRft3H6n/UV5THvpNSii1WYm+7bR8Tl64sAxAdmMvaTeWd+J43hs46nV3wjOi9sPD/cXzpI0ZaHZhrcnZQ9Km79CQulRP0NugO3vOWA0+Yl52+fIk51Wol+vivBkcTsdteyGo/Akl7kJ2BNpBUUFyLtRiOIKQPtsJ/9eM8knXKohPt/HgCdDN2UAtZ0BVXYo4dtyErE5mt85ARaa8xan2nYT9g9GmJ0P5267PM+b821JHJOvDQYTj37Q0Sg+6VSlAoLKIfEsK8HXyVHjr2JlE7AndndCBtYgtuAcM67GGkEBNqcGW4asqimf0fv9M9g9/7Z3GDFU235NpIYB112rR3KqppIRMYC5MJ5nyM8JowUybs4/S2+f7nA+3+HdLI9AqY5hLw11MeohVz4MTOdSClZBkY16GH1q9x59EReoAIMhmQ/KhpZTcNE8kczIem/7gEIYQSJFA7+N4u2xEoHX0+HgDrwzD5ND5aaxUm0UHibmjd448Afs5xUI=
