# Project information
site_name: 'Open FinTech'
site_description: 'Open FinTech public documentation'
site_author: 'Open FinTech (c)'
site_url: 'https://openfintech.io/'

# Repository
repo_name: 'openfintechio/openfintech'
repo_url: 'https://github.com/openfintechio/openfintech'
edit_uri: ""

# Copyright
copyright: '© 2016-2048 Open FinTech. All Rights Reserved.'

# Configuration
theme:
  favicon: images/favicon/favicon-32x32.png
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  #feature:
  #  tabs: true
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra_css:
  - extra.css

# Google Analytics
google_analytics:
  - 'UA-72023338-3'
  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: openfintech-io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details

nav:
  - Introduction: index.md
  - Payment Providers: payment-providers/index.md
  - Payment Methods: payment-methods/index.md
  - Payment Services: payment-services/index.md
  - Payout Methods: payout-methods/index.md
  - Payout Services: payout-services/index.md
  - Vendors: vendors/index.md
  - Currencies: currencies/index.md
