site_name: 'Documentation'
site_description: 'OpenFinTech.io public documentation'
site_author: 'OpenFinTech.io (c)'
copyright: '© 2016-2048 OpenFinTech.io<sup>®</sup>. All Rights Reserved.'

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
extra_css:
  - extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: paycoreio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details

nav:
